# schema https://raw.githubusercontent.com/hexidedigital/laravel-gitlab-deploy/develop/schema/deploy-prepare-v1.json

# How to work with the file, read here
# https://github.com/hexidedigital/laravel-gitlab-deploy#prepare

version: 1

# Repository configurations
git-lab:
  project:
    # Read where to get this token - https://github.com/hexidedigital/laravel-gitlab-deploy#gitlab-api-access-token
    token: "XXXXXXXXXX"

    # Read about the possible options https://github.com/hexidedigital/laravel-gitlab-deploy#project-full-name-or-id
    project-id: "NAMESPACE/PROJECT_NAME"
    # project-id: "000000"

    domain: https://gitlab.hexide-digital.com


# Server configurations
stages:
  # Stage name to prepare command
  - name: dev
    options:
      git-url: git@gitlab.hexide-digital.com:NAMESPACE/PROJECT_NAME.git
      base-dir-pattern: "/home/{{USER}}/web/{{HOST}}/public_html"
      bin-composer: /usr/bin/php8.1 /usr/bin/composer
      bin-php: /usr/bin/php8.1

    server:
      ssh-port: 22
      domain: https://example.com
      host: example.com
      login: example-user
      password: XXXXXXXXXX

    database:
      database: proj_db
      username: proj_db
      password: XXXXXXXXXX

    # mail:
    #   hostname: devs.hexide-digital.com
    #   username: template@host
    #   password: mail_pass
